[package]
name = "kitty-sessionizer"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "kitty-sessionizer"
path = "src/main.rs"

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = "z"
panic = "abort"

[dependencies]
clap = "4.5.18"
serde_json = "1.0.128"
